---
- hosts: Virtual
  remote_user: emperor
  become: yes
  tasks:
    - name: "Instalando zabbix-agent"
      apt:
        name: zabbix-agent
        state: present

    - name: "Removendo arquivo de configuração existente"
      file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent

    - name: "Criando novo arquivo de configuração do Zabbix Agent"
      copy:
        dest: /etc/zabbix/zabbix_agentd.conf
        content: |
          PidFile=/run/zabbix/zabbix_agentd.pid
          LogFile=/var/log/zabbix-agent/zabbix_agentd.log
          LogFileSize=0
          Server=P7829207420,P9323749494.vsw0,P9323749494.vsw1
          ServerActive=P7829207420
          Include=/etc/zabbix/zabbix_agentd.conf.d/*.conf

    - name: "Reiniciando Zabbix Agent"
      service:
        name: zabbix-agent
        state: restarted